### ISSUE TITLE
Focus Indicator

### ISSUE THREAD

**Issue by bokster** [wvuweb/wvu-design-system#27]
Currently, the default focus style for Chrome and Safari is a blue outline (obvious) while Firefox has a dotted outline (not obvious). I haven't looked at browsers on a PC. It would be great if we could make the focus style consistent on all the browsers. 

**Chrome**
![screen shot 2019-03-01 at 8 19 36 am](https://user-images.githubusercontent.com/289061/53645889-ecfdbb80-3c07-11e9-852c-dd2a9e06fca0.png)
**Safari**
![screen shot 2019-03-01 at 8 20 14 am](https://user-images.githubusercontent.com/289061/53645888-ecfdbb80-3c07-11e9-829f-3785281d6a90.png) 
**Firefox**
![screen shot 2019-03-01 at 8 18 13 am](https://user-images.githubusercontent.com/289061/53645890-ecfdbb80-3c07-11e9-9132-a4aab38a14a4.png)

It would be great if we could make the focus style consistent on all the browsers. An example is [https://a11y-style-guide.com/style-guide/section-resources.html](url)

**Comment by adamjohnson** [comment]
That same site has a section on [Link Focus](https://a11y-style-guide.com/style-guide/section-general.html#kssref-general-link-focus) along with code that will help keep the focus style consistent across browsers:

```scss
a:focus {
   outline: auto 2px Highlight; // for non-webkit browsers
   outline: auto 5px -webkit-focus-ring-color; // for webkit browsers
 }
```
