### ISSUE TITLE
Finish adding comments to all partials.

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-design-system#69]

**Comment by adamjohnson** [comment]
This should be done in Sass partials too. 

This [media query mixin](https://github.com/wvuweb/brand-patterns/blob/master/scss/1-base/_wvu-media-queries.scss) does a good job of explaining what options are available and (perhaps more importantly) usage examples of how to use the mixin.

Code example:

```scss
// Title
//==================================================
// Description

@mixin myMixin($option-a: red) {
  color: $option-a;
}

// Usage example (if it's a mixin):
// .example {
//   @include myMixin($option-a: blue);
// }
```

Just by looking, I don't know what `_wvu-bar.scss` or `wvu-logo-lockup.scss` do without exploring beyond a first glance. Structuring our Sass partials to have a title, description and, optionally, a usage example will help.
