### ISSUE TITLE
Make !important configurable.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system#78]
Right now, `!important` is applied to a lot of rules--likely intentionally.

Sometimes, users might not want to add `!important` to rules in their project. It'd be nice to be able to turn this on/of globally, or on a per mixin basis.

Code example:

```scss
$global-important: !important !default;
@mixin myMixin($is-important: $global-important) {
  color: red $is-important;
}

.example {
  @include myMixin();
  font-size: 16px $global-important;
}
```

Outputs:

```css
.example {
  color: red !important;
  font-size: 16px !important;
}
```

Users will be able to explicitly override `!important` on a per mixin basis by doing:

```scss
.example-2 {
  @include myMixin($is-important: null); // `null` is used to omit `!important`
}
```
